const SHOW_THEME_SWITCHER = false
const SHOW_INSTALL_PROMPT = false
const DEFAULT_THEME = 'dark'
const DEFAULT_LANGUAGE = 'en'
const SHOW_VERSION_UPDATE_NOTIFICATION = false
const SHOW_SPLASH_SCREEN = false

export {
    SHOW_THEME_SWITCHER,
    SHOW_INSTALL_PROMPT,
    DEFAULT_THEME,
    DEFAULT_LANGUAGE,
    SHOW_VERSION_UPDATE_NOTIFICATION,
    SHOW_SPLASH_SCREEN
}